/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body3
 */
export interface Body3 {
    /**
     * None
     * @type {number}
     * @memberof Body3
     */
    integer?: any;
    /**
     * None
     * @type {number}
     * @memberof Body3
     */
    int32?: any;
    /**
     * None
     * @type {number}
     * @memberof Body3
     */
    int64?: any;
    /**
     * None
     * @type {number}
     * @memberof Body3
     */
    number: any;
    /**
     * None
     * @type {number}
     * @memberof Body3
     */
    _float?: any;
    /**
     * None
     * @type {number}
     * @memberof Body3
     */
    _double: any;
    /**
     * None
     * @type {string}
     * @memberof Body3
     */
    string?: any;
    /**
     * None
     * @type {string}
     * @memberof Body3
     */
    patternWithoutDelimiter: any;
    /**
     * None
     * @type {string}
     * @memberof Body3
     */
    _byte: any;
    /**
     * None
     * @type {string}
     * @memberof Body3
     */
    binary?: any;
    /**
     * None
     * @type {string}
     * @memberof Body3
     */
    date?: any;
    /**
     * None
     * @type {Date}
     * @memberof Body3
     */
    dateTime?: any;
    /**
     * None
     * @type {string}
     * @memberof Body3
     */
    password?: any;
    /**
     * None
     * @type {string}
     * @memberof Body3
     */
    callback?: any;
}
