/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Model for testing model name same as property name
 * @export
 * @interface Name
 */
export interface Name {
    /**
     * 
     * @type {number}
     * @memberof Name
     */
    name: any;
    /**
     * 
     * @type {number}
     * @memberof Name
     */
    snakeCase?: any;
    /**
     * 
     * @type {string}
     * @memberof Name
     */
    property?: any;
    /**
     * 
     * @type {number}
     * @memberof Name
     */
    _123Number?: any;
}
