/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGAmount.h
 *
 * some description 
 */

#ifndef SWGAmount_H_
#define SWGAmount_H_

#include <QJsonObject>


#include "SWGCurrency.h"

#include "SWGObject.h"

namespace Swagger {

class SWGAmount: public SWGObject {
public:
    SWGAmount();
    SWGAmount(QString json);
    ~SWGAmount();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    SWGAmount* fromJson(QString jsonString) override;

    double getValue();
    void setValue(double value);

    SWGCurrency* getCurrency();
    void setCurrency(SWGCurrency* currency);


    virtual bool isSet() override;

private:
    double value;
    bool m_value_isSet;

    SWGCurrency* currency;
    bool m_currency_isSet;

};

}

#endif /* SWGAmount_H_ */
