/**
 * Swagger Petstore *_/ ' \" =end -- \\r\\n \\n \\r
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  *_/ ' \" =end --       
 *
 * OpenAPI spec version: 1.0.0 *_/ ' \" =end -- \\r\\n \\n \\r
 * Contact: apiteam@swagger.io *_/ ' \" =end -- \\r\\n \\n \\r
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Return.h
 * 
 * Model for testing reserved words  *_/ &#39; \&quot; &#x3D;end -- \\r\\n \\n \\r
 */

#ifndef Return_H_
#define Return_H_

#include <QJsonObject>



#include "SWGObject.h"


namespace Swagger {

class Return: public SWGObject {
public:
    Return();
    Return(QString* json);
    virtual ~Return();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    Return* fromJson(QString &jsonString);

    qint32 getReturn();
    void setReturn(qint32 return);


private:
    qint32 return;
};

} /* namespace Swagger */

#endif /* Return_H_ */
