/**
 * Swagger Petstore *_/ ' \" =end -- \\r\\n \\n \\r
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  *_/ ' \" =end --       
 *
 * OpenAPI spec version: 1.0.0 *_/ ' \" =end -- \\r\\n \\n \\r
 * Contact: apiteam@swagger.io *_/ ' \" =end -- \\r\\n \\n \\r
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_OBJECT_H_
#define _SWG_OBJECT_H_

#include <QJsonObject>

namespace Swagger {

class SWGObject {
  public:
    virtual QJsonObject asJsonObject() {
      return QJsonObject();
    }
    virtual ~SWGObject() {}
    virtual SWGObject* fromJson(QString jsonString) {
        Q_UNUSED(jsonString);
        return new SWGObject();
    }
    virtual void fromJsonObject(QJsonObject json) {
        Q_UNUSED(json);
    }
    virtual QString asJson() {
        return QString("");
    }
    virtual bool isSet() {
        return false;
    }
};

}

#endif /* _SWG_OBJECT_H_ */
