/**
 * Swagger Petstore *_/ ' \" =end -- \\r\\n \\n \\r
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  *_/ ' \" =end --       
 *
 * OpenAPI spec version: 1.0.0 *_/ ' \" =end -- \\r\\n \\n \\r
 * Contact: apiteam@swagger.io *_/ ' \" =end -- \\r\\n \\n \\r
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef SWG_QOBJECT_WRAPPER_H
#define SWG_QOBJECT_WRAPPER_H

#include <QObject>

namespace Swagger {

    template <typename ObjectT>
    class SWGQObjectWrapper : public QObject {
        public:
            SWGQObjectWrapper(ObjectT t){
                data = t;
            }
            ~SWGQObjectWrapper(){

            }
        private :
            ObjectT data;
    };
    template <typename ObjectT>
    class SWGQObjectWrapper<ObjectT*> : public QObject {
        public:
            SWGQObjectWrapper(ObjectT* t){
                data = t;
            }
            ~SWGQObjectWrapper(){
                delete data;
            }
        private :
            ObjectT* data;
    };

}

#endif // SWG_QOBJECT_WRAPPER_H