/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
*
* OpenAPI spec version: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.apis

import com.google.gson.Gson
import io.ktor.application.call
import io.ktor.auth.UserIdPrincipal
import io.ktor.auth.authentication
import io.ktor.auth.authenticate
import io.ktor.auth.OAuthAccessTokenResponse
import io.ktor.auth.OAuthServerSettings
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.delete
import io.ktor.locations.get
import io.ktor.locations.post
import io.ktor.locations.put
import io.ktor.locations.patch
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.Route
import io.ktor.routing.route

import io.swagger.server.Paths
import io.swagger.server.infrastructure.ApiPrincipal


import io.swagger.server.models.ApiResponse
import io.swagger.server.models.Pet

@KtorExperimentalLocationsAPI
fun Route.PetApi() {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()
    post<Paths.addPet> {  _: Paths.addPet ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    call.respond(HttpStatusCode.NotImplemented)
}

    }
    delete<Paths.deletePet> {  _: Paths.deletePet ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    call.respond(HttpStatusCode.NotImplemented)
}

    }
    get<Paths.findPetsByStatus> {  _: Paths.findPetsByStatus ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    val exampleContentType = "application/xml"
    val exampleContentString = """<Pet>
      <id>123456789</id>
      <name>doggie</name>
      <photoUrls>
        <photoUrls>aeiou</photoUrls>
      </photoUrls>
      <tags>
      </tags>
      <status>aeiou</status>
    </Pet>"""
    
    when(exampleContentType) {
        "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
        "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
        else -> call.respondText(exampleContentString)
    }
}

    }
    get<Paths.findPetsByTags> {  _: Paths.findPetsByTags ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    val exampleContentType = "application/xml"
    val exampleContentString = """<Pet>
      <id>123456789</id>
      <name>doggie</name>
      <photoUrls>
        <photoUrls>aeiou</photoUrls>
      </photoUrls>
      <tags>
      </tags>
      <status>aeiou</status>
    </Pet>"""
    
    when(exampleContentType) {
        "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
        "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
        else -> call.respondText(exampleContentString)
    }
}

    }
    get<Paths.getPetById> {  _: Paths.getPetById ->
        val principal = call.authentication.principal<ApiPrincipal>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    val exampleContentType = "application/xml"
    val exampleContentString = """<Pet>
      <id>123456789</id>
      <name>doggie</name>
      <photoUrls>
        <photoUrls>aeiou</photoUrls>
      </photoUrls>
      <tags>
      </tags>
      <status>aeiou</status>
    </Pet>"""
    
    when(exampleContentType) {
        "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
        "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
        else -> call.respondText(exampleContentString)
    }
}

    }
    put<Paths.updatePet> {  _: Paths.updatePet ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    call.respond(HttpStatusCode.NotImplemented)
}

    }
    post<Paths.updatePetWithForm> {  _: Paths.updatePetWithForm ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    call.respond(HttpStatusCode.NotImplemented)
}

    }
    post<Paths.uploadFile> {  _: Paths.uploadFile ->
        val principal = call.authentication.principal<OAuthAccessTokenResponse>()

if (principal == null) {
    call.respond(HttpStatusCode.Unauthorized)
} else {
    val exampleContentType = "application/json"
    val exampleContentString = """{"empty": false}"""
    
    when(exampleContentType) {
        "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
        "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
        else -> call.respondText(exampleContentString)
    }
}

    }
}
