# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule SwaggerPetstore.Model.User do
  @moduledoc """
  
  """

  @derive [Poison.Encoder, Poison.Decoder]
  defstruct [
    :"id",
    :"username",
    :"firstName",
    :"lastName",
    :"email",
    :"password",
    :"phone",
    :"userStatus"
  ]
end

