/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.3-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "Amount.h"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace io {
namespace swagger {
namespace server {
namespace model {

Amount::Amount()
{
    m_Value = 0.0;
    
}

Amount::~Amount()
{
}

std::string Amount::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	pt.put("Value", m_Value);
	write_json(ss, pt, false);
	return ss.str();
}

void Amount::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	m_Value = pt.get("Value", 0.0);
}

double Amount::getValue() const
{
    return m_Value;
}
void Amount::setValue(double value)
{
    m_Value = value;
}
std::shared_ptr<Currency> Amount::getCurrency() const
{
    return m_Currency;
}
void Amount::setCurrency(std::shared_ptr<Currency> value)
{
    m_Currency = value;
}

}
}
}
}

