# coding: utf-8

"""
    Swagger Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.single_pet_response import SinglePetResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestSinglePetResponse(unittest.TestCase):
    """SinglePetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSinglePetResponse(self):
        """Test SinglePetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.single_pet_response.SinglePetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
