# coding: utf-8

"""
    Swagger Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.nullable_enum_model import NullableEnumModel  # noqa: E501
from swagger_client.rest import ApiException


class TestNullableEnumModel(unittest.TestCase):
    """NullableEnumModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNullableEnumModel(self):
        """Test NullableEnumModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.nullable_enum_model.NullableEnumModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
