<?php
/**
 * FakeApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Petstore *_/ ' \" =end -- \\r\\n \\n \\r
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  *_/ ' \" =end --
 *
 * OpenAPI spec version: 1.0.0 *_/ ' \" =end -- \\r\\n \\n \\r
 * Contact: apiteam@swagger.io *_/ ' \" =end -- \\r\\n \\n \\r
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\ResponseInterface;
use Swagger\Client\ApiException;
use Swagger\Client\MappedApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * FakeApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FakeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

	/**
	 * Returns the un-boxed content from an response.
	 *
	 * @param ResponseInterface $response
	 * @param string $targetType
	 *
	 * @return object|\Psr\Http\Message\StreamInterface|string
	 */
    protected function getContent(ResponseInterface $response, string $targetType)
    {
        $responseBody = $response->getBody();
        if ($targetType === '\SplFileObject') {
            return $responseBody; //stream goes to serializer
        } else {
            if ($targetType === 'string') {
                return $responseBody->getContents();
            }
            // by default we expect json content
            return json_decode($responseBody->getContents());
        }
    }

	/**
	 * Receive the content for operation result.
	 *
	 * @param string $operationId
	 * @param ResponseInterface $response
	 * @param string $defaultModel
	 *
	 * @return mixed
	 */
	protected function getResponseData(string $operationId, ResponseInterface $response, string $defaultModel = null)
	{
		$statusCode = $response->getStatusCode();
		$targetModel = null;

		if ($mapping = constant('self::' . $operationId . 'CodeMapping')) {
			if (isset($mapping[$statusCode])) {
				$targetModel = $mapping[$statusCode];
			} else if (isset($mapping['default'])) {
				$targetModel = $mapping['default'];
			}
		}

		// fallback for successful call
		if ($defaultModel && !$targetModel && $statusCode >= 200 && $statusCode <= 299) {
			$targetModel = $defaultModel;
		}

		if (!$targetModel) {
			throw new \LogicException(
				sprintf(
					'The operation %s has no defined response for status %d.',
					$operationId,
					$statusCode
				)
			);
		}

		return ObjectSerializer::deserialize(
			$this->getContent($response, $targetModel),
			$targetModel,
			$response->getHeaders()
		);
	}

	/**
	 * Receive exception details for failed operation, caused by an response.
	 *
	 * @param string $operationId
	 * @param ResponseInterface $response
	 * @param RequestException|null $exception
	 *
	 * @return ApiException
	 */
	protected function getResponseException(string $operationId, ResponseInterface $response = null, RequestException $exception = null): ApiException
	{
		if ($response) {
			try {
				// we try to map the exception according to the specification rules
				return new MappedApiException(
					$this->getResponseData($operationId, $response),
					sprintf('Operation %s was not successful. Code: %s', $operationId, $response->getStatusCode()),
					$response->getStatusCode(),
					$response,
					$exception
				);
			} catch (\LogicException $notMappedCode) {
				// there is no mapping available, but we have a response
				return new ApiException(
					sprintf(
						'Operation %s was not successful and it\'s response data was not mapped. Code: %s %s',
						$operationId,
						$response->getStatusCode(),
                        $exception ? $exception->getMessage() : ''
					),
					$response->getStatusCode(),
					$response,
					$exception
				);
			}
		}
		// unspecific exception, as we don't know about it's nature
		return new ApiException(
			sprintf(
                'Operation %s was not successful. Code: %s %s',
                $operationId,
                $response ? $response->getStatusCode() : -1,
                $exception ? $exception->getMessage() : ''
            ),
			$response ? $response->getStatusCode() : -1,
			$response,
			$exception
		);
	}

    /**
     * Operation testCodeInjectEndRnNR
     *
     * To test code injection *_/ ' \" =end -- \\r\\n \\n \\r
     *
     * @param  string $test_code_inject____end____rn_n_r To test code injection *_/ &#39; \&quot; &#x3D;end -- \\r\\n \\n \\r (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function testCodeInjectEndRnNR($test_code_inject____end____rn_n_r = null) : void
    {
        $this->testCodeInjectEndRnNRWithHttpInfo($test_code_inject____end____rn_n_r);
    }

    /**
     * Operation testCodeInjectEndRnNRWithHttpInfo
     *
     * To test code injection *_/ ' \" =end -- \\r\\n \\n \\r
     *
     * @param  string $test_code_inject____end____rn_n_r To test code injection *_/ &#39; \&quot; &#x3D;end -- \\r\\n \\n \\r (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function testCodeInjectEndRnNRWithHttpInfo($test_code_inject____end____rn_n_r = null)
    {
        $request = $this->testCodeInjectEndRnNRRequest($test_code_inject____end____rn_n_r);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $requestException) {
            throw $this->getResponseException('testCodeInjectEndRnNR', $requestException->getResponse(), $requestException);
        }

        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw $this->getResponseException('testCodeInjectEndRnNR', $response);
        }

        return [null, $statusCode, $response->getHeaders()];
    }

    /**
     * Operation testCodeInjectEndRnNRAsync
     *
     * To test code injection *_/ ' \" =end -- \\r\\n \\n \\r
     *
     * @param  string $test_code_inject____end____rn_n_r To test code injection *_/ &#39; \&quot; &#x3D;end -- \\r\\n \\n \\r (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function testCodeInjectEndRnNRAsync($test_code_inject____end____rn_n_r = null)
    {
        return $this->testCodeInjectEndRnNRAsyncWithHttpInfo($test_code_inject____end____rn_n_r)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation testCodeInjectEndRnNRAsyncWithHttpInfo
     *
     * To test code injection *_/ ' \" =end -- \\r\\n \\n \\r
     *
     * @param  string $test_code_inject____end____rn_n_r To test code injection *_/ &#39; \&quot; &#x3D;end -- \\r\\n \\n \\r (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function testCodeInjectEndRnNRAsyncWithHttpInfo($test_code_inject____end____rn_n_r = null)
    {
        $returnType = '';
        $request = $this->testCodeInjectEndRnNRRequest($test_code_inject____end____rn_n_r);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'testCodeInjectEndRnNR'
     *
     * @param  string $test_code_inject____end____rn_n_r To test code injection *_/ &#39; \&quot; &#x3D;end -- \\r\\n \\n \\r (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function testCodeInjectEndRnNRRequest($test_code_inject____end____rn_n_r = null)
    {

        $resourcePath = '/fake';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // form params
        if ($test_code_inject____end____rn_n_r !== null) {
            $formParams['test code inject */ &#39; &quot; &#x3D;end -- \r\n \n \r'] = ObjectSerializer::toFormValue($test_code_inject____end____rn_n_r);
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', '*_/  \" =end --']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', '*_/  \" =end --'],
                ['application/json', '*_/  \" =end --']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
