//
// Definition3.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Definition 3 (recursive) */
open class Definition3: JSONEncodable {
    /** nested Definition3 array */
    public var definition3: [Definition3]?
    /** Content Id for lookup */
    public var id: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Definition3"] = self.definition3?.encodeToJSON()
        nillableDictionary["Id"] = self.id
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
