/**
 * Swagger Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FormatTest { 
    integer?: number;
    int32?: number;
    int64?: number;
    number: number;
    _float?: number;
    _double?: number;
    string?: string;
    _byte: string;
    binary?: Blob;
    date: string;
    dateTime?: Date;
    uuid?: string;
    password: string;
}