//
// ValMemberChoice1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Business Term: Scheme Member Definition: Information about a Member of the Scheme. Purpose: To have enough information to be able to produce a Statement of Account indicating premium due. */
open class ValMemberChoice1: JSONEncodable {
    /** Business Term: Date Of Birth Definition: The date of birth of the member. Purpose: To be able to uniquely identify a member within a scheme. */
    public var valDateOfBirth: ISOFullDate
    /** Business Term: Leaving Date Definition: The date the member left/is due to leave the scheme. Purpose: To identify those members that have left or are due to leave the scheme. To be able to calculate the benefit insured/premium payable in respect of the member/category. */
    public var valLeavingDate: ISOFullDate?


    public init(valDateOfBirth: ISOFullDate, valLeavingDate: ISOFullDate?=nil) {
        self.valDateOfBirth = valDateOfBirth
        self.valLeavingDate = valLeavingDate
    }
    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["val_date_of_birth"] = self.valDateOfBirth.encodeToJSON()
        nillableDictionary["val_leaving_date"] = self.valLeavingDate?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
