name: 'JavaBuild'
description: 'build java with maven'
inputs:
  path:
    description: 'project root path'
    required: true
  job-name:
    description: 'Job name'
    required: true
  build-comands:
    description: 'Build Commands'
    required: true
outputs:
  logs:
    description: "logs"
    value: ${{ steps.build.outputs.logs }}
  path:
    description: "output path"
    value: ${{ steps.build.outputs.path }}
runs:
  using: "composite"
  steps:
    - id: build
      name: build
      run: |
        logfile=${{ inputs.job-name }}.log
        echo "::set-output name=logs::$(echo $logfile)"
        echo "::set-output name=path::$(echo generated/${{ inputs.job-name }})"
        echo -e "\n****** mvn clean package ******\n" >> $logfile
        curdir=$(pwd)
        cd ${{ inputs.path }}
        ${{ inputs.build-comands }} | tee --append $curdir/$logfile
        cd ${curdir}
      shell: bash
