/**
* Swagger Petstore
* This is a sample Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
*
* OpenAPI spec version: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param name Updated name of the pet
 * @param status Updated status of the pet
 */
data class Body (

    /* Updated name of the pet */
    val name: kotlin.String? = null,
    /* Updated status of the pet */
    val status: kotlin.String? = null
) {
}