//
// Boolean.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** True or False indicator */
public enum Boolean: Bool, Codable {
    case _true = "true"
    case _false = "false"

}
